sales_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: sales_user
      password: sales_pass
      port: 5432
      dbname: sales_dw
      schema: analytics
      threads: 4
